# Generated by Django 4.0.4 on 2022-05-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abiandabla',
            fields=[
                ('ab_id', models.FloatField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('abiabla_id', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'abiandabla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dormstudents',
            fields=[
                ('student_id', models.FloatField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('student_phone', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dormstudents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('faculty_id', models.FloatField(primary_key=True, serialize=False)),
                ('fac_title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'faculties',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentCities',
            fields=[
                ('city_id', models.FloatField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'student_cities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tester',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entryrecords',
            fields=[
                ('entry_id', models.FloatField(primary_key=True, serialize=False)),
                ('day', models.CharField(blank=True, max_length=50, null=True)),
                ('out_dorm', models.DateField(blank=True, null=True)),
                ('in_dorm', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.dormstudents')),
            ],
            options={
                'db_table': 'entryrecords',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='dormstudents',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.studentcities'),
        ),
        migrations.AddField(
            model_name='dormstudents',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.faculties'),
        ),
        migrations.CreateModel(
            name='Dormrooms',
            fields=[
                ('room_id', models.FloatField(primary_key=True, serialize=False)),
                ('abiabla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.abiandabla')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.dormstudents')),
            ],
            options={
                'db_table': 'dormrooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('balance_id', models.FloatField(primary_key=True, serialize=False)),
                ('year', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.dormstudents')),
            ],
            options={
                'db_table': 'balance',
                'managed': True,
            },
        ),
    ]
