# Generated by Django 4.0.4 on 2022-05-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_anthony_delete_tester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anthony',
        ),
    ]
