# Generated by Django 4.0.4 on 2022-05-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_anthony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrecords',
            name='entry_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
