# Generated by Django 4.0.4 on 2022-05-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_entryrecords_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormstudents',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
