# Generated by Django 4.0.4 on 2022-05-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_abiandabla_ab_id_alter_dormrooms_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiandabla',
            name='ab_id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dormrooms',
            name='room_id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dormstudents',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
