# Generated by Django 4.0.4 on 2022-05-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_abiandabla_ab_id_alter_dormrooms_room_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abiandabla',
            old_name='abiabla_id',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='entryrecords',
            name='day',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
