# Generated by Django 4.0.4 on 2022-05-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_abiabla_id_abiandabla_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormrooms',
            old_name='student',
            new_name='student_id',
        ),
    ]
