# Generated by Django 4.0.4 on 2022-05-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_student_dormrooms_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormrooms',
            old_name='student_id',
            new_name='student',
        ),
    ]
